### PR TITLE
Added SSDT-TB3.aml to support TB3 hot plug

### PR DESCRIPTION
**Pull request by XinJiangCN**
Thanks for your config! It works pretty well.

I found an TB3 fix for Z390 and I modified it to support the phantom x570 itx mobo. Now it supports hot plug and device switch with no problem on my desktop.

### CODE REVIEW

**Comment by aluveitie** [comment]
Wow, thats great to hear! Thanks for the pull request 👍

**Comment by XinJiangCN** [comment]
BTW, just found TB3 devices don't need to be plugged in during boot to get it work by using this SSDT!

**Comment by aluveitie** [comment]
Great, I currently don't have my dongle at hand to test it but there are some users with this board using TB 3 that should be very happy to hear this :)

**Comment by aluveitie** [comment]
One thing I've quickly tested: even with this SSDT MacOS does a reboot when waking up from sleep. I have to disable both the GP13 USB controller and Thunderbolt controller for it to wakeup properly.

**Comment by XinJiangCN** [comment]
> One thing I've quickly tested: even with this SSDT MacOS does a reboot when waking up from sleep. I have to disable both the GP13 USB controller and Thunderbolt controller for it to wakeup properly.

I haven't tried the sleep and I cannot manage to sleep even without the new SSDT. The controller might not be mapped correctly. Will work on that in the future

**Comment by aluveitie** [comment]
It's not an issue with the SSDT. I've tried everything, but I could only get wakeup without an automatic reboot once I've disabled the GB13.XHC0 USB and the Thunderbolt controller.
If either one of them is enabled wakeup ends in an immediate reboot.

If you find some way around that would be great, a lot of people have issues with that USB controller (not just on this board).

**Comment by XinJiangCN** [comment]
Actually I found a potential solution for the wake up issue with TB controller. 

[You can check this](https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-3)

There is a native way to support the Thunderbolt by replacing the firmware in macOS with the stock firmware of the controller. I've found the FW for JHL7340 at [here](https://github.com/XinJiangCN/PHANTOM-X570-ITX-Hackintosh/blob/master/Firmware/Mac-0x001A-B2_2.46.0.16-C1_55.2.bin), but I don't know how to flash it. If you have any idea or would like to try it would be appreciated!

**Comment by aluveitie** [comment]
I think you have to physically connect to the TB chips pins to flash it. Two guys had a lengthy thread in the AMD OSX Forum working on the Creator board. They basically gave up after a failed flash destroyed the chip and did not want to bother manually replacing it.

They are now on Gigabyte boards with TB addon cards that are easier to flash. Some guys in the German Hackintosh Forum also have developed a Firmware to flash such cards to get them work natively.

**Pull request merged**
